// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDFR5lWdafYQQDEIthKjN59E3rbrDQ6JE',
    appId: '1:149386374618:web:f15726439ee88a4f2e64e3',
    messagingSenderId: '149386374618',
    projectId: 'fruit-e-commerce-9f8a1',
    authDomain: 'fruit-e-commerce-9f8a1.firebaseapp.com',
    storageBucket: 'fruit-e-commerce-9f8a1.firebasestorage.app',
    measurementId: 'G-Z68EX26R2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvKHW_8LpeSnqs2_4kUlW-iHRhn1rVaKI',
    appId: '1:149386374618:android:cf21f574f9aef47c2e64e3',
    messagingSenderId: '149386374618',
    projectId: 'fruit-e-commerce-9f8a1',
    storageBucket: 'fruit-e-commerce-9f8a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdYLip1fGj7WZbEnYtHAjB6Ti-k4jlEtc',
    appId: '1:149386374618:ios:8be966e193c93e852e64e3',
    messagingSenderId: '149386374618',
    projectId: 'fruit-e-commerce-9f8a1',
    storageBucket: 'fruit-e-commerce-9f8a1.firebasestorage.app',
    iosBundleId: 'com.example.fruitMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdYLip1fGj7WZbEnYtHAjB6Ti-k4jlEtc',
    appId: '1:149386374618:ios:8be966e193c93e852e64e3',
    messagingSenderId: '149386374618',
    projectId: 'fruit-e-commerce-9f8a1',
    storageBucket: 'fruit-e-commerce-9f8a1.firebasestorage.app',
    iosBundleId: 'com.example.fruitMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDFR5lWdafYQQDEIthKjN59E3rbrDQ6JE',
    appId: '1:149386374618:web:c52f07660d2ba7692e64e3',
    messagingSenderId: '149386374618',
    projectId: 'fruit-e-commerce-9f8a1',
    authDomain: 'fruit-e-commerce-9f8a1.firebaseapp.com',
    storageBucket: 'fruit-e-commerce-9f8a1.firebasestorage.app',
    measurementId: 'G-DMGH2VBYHH',
  );
}
